var = input("digite algo")
print(type(var))
print(var.isalnum())
print(var.isalpha())
print(var.isdigit())
print(var.isnumeric())
print(var.islower())
print(var.isupper())
print(var.isspace())
print(var.isidentifier())
print(var.isprintable())